@OnlineShop_HostAddress = http://localhost:5021

GET {{OnlineShop_HostAddress}}/api/products

### Obtener lista de tiendas
GET {{OnlineShop_HostAddress}}/api/stores

### Obtener lista de relaciones entre tiendas y productos
GET {{OnlineShop_HostAddress}}/api/storeproducts

### Crear una nueva relación entre tienda y producto
POST {{OnlineShop_HostAddress}}/api/storeproducts
Content-Type: application/json

{
  "StoreId": 2,
  "ProductId": 2,
  "Stock": 1
}

### Modificar la cantidad de stock de una relación existente
PUT {{OnlineShop_HostAddress}}/api/storeproducts/2/2
Content-Type: application/json

{
  "Stock": 5
}

### Obtener la relación entre la tienda 2 y el producto 2
GET {{OnlineShop_HostAddress}}/api/storeproducts/2/2

### Eliminar la relación entre la tienda 2 y el producto 2
DELETE {{OnlineShop_HostAddress}}/api/storeproducts/2/2

### Crear un nuevo producto
POST {{OnlineShop_HostAddress}}/api/products
Content-Type: application/json

{
  "Name": "Nuevo Producto",
  "Size": "M",
  "Color": "Azul",
  "Price": "20",
  "Description": "Nuevo producto en la tienda"
}

### Obtener el producto recién creado
GET {{OnlineShop_HostAddress}}/api/products/3

### Eliminar el producto recién creado
DELETE {{OnlineShop_HostAddress}}/api/products/3

### Crear una nueva tienda
POST {{OnlineShop_HostAddress}}/api/stores
Content-Type: application/json

{
  "Id" : 1,
  "Name": "Nueva Tienda",
  "Location": "Nueva Ubicación"
}

### Obtener la tienda recién creada
GET {{OnlineShop_HostAddress}}/api/stores/0

### Eliminar la tienda recién creada
DELETE {{OnlineShop_HostAddress}}/api/stores/2
